// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.3
// source: dashboard.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DashboardService_GetPersonalAccessCount_FullMethodName            = "/auth.DashboardService/GetPersonalAccessCount"
	DashboardService_GetTotalPersonalBookingRevenue_FullMethodName    = "/auth.DashboardService/GetTotalPersonalBookingRevenue"
	DashboardService_GetAccessCountBySubscriptionID_FullMethodName    = "/auth.DashboardService/GetAccessCountBySubscriptionID"
	DashboardService_GetBookingRevenueBySubscriptionID_FullMethodName = "/auth.DashboardService/GetBookingRevenueBySubscriptionID"
)

// DashboardServiceClient is the client API for DashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DashboardServiceClient interface {
	GetPersonalAccessCount(ctx context.Context, in *AccessCountReq, opts ...grpc.CallOption) (*AccessCountRes, error)
	GetTotalPersonalBookingRevenue(ctx context.Context, in *TotalRevenueReq, opts ...grpc.CallOption) (*TotalRevenueRes, error)
	GetAccessCountBySubscriptionID(ctx context.Context, in *SubscriptionCountReq, opts ...grpc.CallOption) (*SubscriptionCountRes, error)
	GetBookingRevenueBySubscriptionID(ctx context.Context, in *TotalRevenueBySubscriptionReq, opts ...grpc.CallOption) (*TotalRevenueBySubscriptionRes, error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) GetPersonalAccessCount(ctx context.Context, in *AccessCountReq, opts ...grpc.CallOption) (*AccessCountRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessCountRes)
	err := c.cc.Invoke(ctx, DashboardService_GetPersonalAccessCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetTotalPersonalBookingRevenue(ctx context.Context, in *TotalRevenueReq, opts ...grpc.CallOption) (*TotalRevenueRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TotalRevenueRes)
	err := c.cc.Invoke(ctx, DashboardService_GetTotalPersonalBookingRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetAccessCountBySubscriptionID(ctx context.Context, in *SubscriptionCountReq, opts ...grpc.CallOption) (*SubscriptionCountRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionCountRes)
	err := c.cc.Invoke(ctx, DashboardService_GetAccessCountBySubscriptionID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetBookingRevenueBySubscriptionID(ctx context.Context, in *TotalRevenueBySubscriptionReq, opts ...grpc.CallOption) (*TotalRevenueBySubscriptionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TotalRevenueBySubscriptionRes)
	err := c.cc.Invoke(ctx, DashboardService_GetBookingRevenueBySubscriptionID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServiceServer is the server API for DashboardService service.
// All implementations must embed UnimplementedDashboardServiceServer
// for forward compatibility.
type DashboardServiceServer interface {
	GetPersonalAccessCount(context.Context, *AccessCountReq) (*AccessCountRes, error)
	GetTotalPersonalBookingRevenue(context.Context, *TotalRevenueReq) (*TotalRevenueRes, error)
	GetAccessCountBySubscriptionID(context.Context, *SubscriptionCountReq) (*SubscriptionCountRes, error)
	GetBookingRevenueBySubscriptionID(context.Context, *TotalRevenueBySubscriptionReq) (*TotalRevenueBySubscriptionRes, error)
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDashboardServiceServer struct{}

func (UnimplementedDashboardServiceServer) GetPersonalAccessCount(context.Context, *AccessCountReq) (*AccessCountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersonalAccessCount not implemented")
}
func (UnimplementedDashboardServiceServer) GetTotalPersonalBookingRevenue(context.Context, *TotalRevenueReq) (*TotalRevenueRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalPersonalBookingRevenue not implemented")
}
func (UnimplementedDashboardServiceServer) GetAccessCountBySubscriptionID(context.Context, *SubscriptionCountReq) (*SubscriptionCountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessCountBySubscriptionID not implemented")
}
func (UnimplementedDashboardServiceServer) GetBookingRevenueBySubscriptionID(context.Context, *TotalRevenueBySubscriptionReq) (*TotalRevenueBySubscriptionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookingRevenueBySubscriptionID not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}
func (UnimplementedDashboardServiceServer) testEmbeddedByValue()                          {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServiceServer will
// result in compilation errors.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	// If the following call pancis, it indicates UnimplementedDashboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_GetPersonalAccessCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetPersonalAccessCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetPersonalAccessCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetPersonalAccessCount(ctx, req.(*AccessCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetTotalPersonalBookingRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalRevenueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetTotalPersonalBookingRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetTotalPersonalBookingRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetTotalPersonalBookingRevenue(ctx, req.(*TotalRevenueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetAccessCountBySubscriptionID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetAccessCountBySubscriptionID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetAccessCountBySubscriptionID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetAccessCountBySubscriptionID(ctx, req.(*SubscriptionCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetBookingRevenueBySubscriptionID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalRevenueBySubscriptionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetBookingRevenueBySubscriptionID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetBookingRevenueBySubscriptionID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetBookingRevenueBySubscriptionID(ctx, req.(*TotalRevenueBySubscriptionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPersonalAccessCount",
			Handler:    _DashboardService_GetPersonalAccessCount_Handler,
		},
		{
			MethodName: "GetTotalPersonalBookingRevenue",
			Handler:    _DashboardService_GetTotalPersonalBookingRevenue_Handler,
		},
		{
			MethodName: "GetAccessCountBySubscriptionID",
			Handler:    _DashboardService_GetAccessCountBySubscriptionID_Handler,
		},
		{
			MethodName: "GetBookingRevenueBySubscriptionID",
			Handler:    _DashboardService_GetBookingRevenueBySubscriptionID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dashboard.proto",
}
