// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.23.3
// source: dashboard.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessCountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GymId     string `protobuf:"bytes,1,opt,name=gymId,proto3" json:"gymId,omitempty"`
	StartDate string `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate   string `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
}

func (x *AccessCountReq) Reset() {
	*x = AccessCountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCountReq) ProtoMessage() {}

func (x *AccessCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCountReq.ProtoReflect.Descriptor instead.
func (*AccessCountReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *AccessCountReq) GetGymId() string {
	if x != nil {
		return x.GymId
	}
	return ""
}

func (x *AccessCountReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AccessCountReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type AccessCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessDate  string `protobuf:"bytes,1,opt,name=accessDate,proto3" json:"accessDate,omitempty"`
	AccessCount int32  `protobuf:"varint,2,opt,name=accessCount,proto3" json:"accessCount,omitempty"`
}

func (x *AccessCount) Reset() {
	*x = AccessCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCount) ProtoMessage() {}

func (x *AccessCount) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCount.ProtoReflect.Descriptor instead.
func (*AccessCount) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *AccessCount) GetAccessDate() string {
	if x != nil {
		return x.AccessDate
	}
	return ""
}

func (x *AccessCount) GetAccessCount() int32 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

type AccessCountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessCountList []*AccessCount `protobuf:"bytes,1,rep,name=accessCountList,proto3" json:"accessCountList,omitempty"`
}

func (x *AccessCountRes) Reset() {
	*x = AccessCountRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessCountRes) ProtoMessage() {}

func (x *AccessCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessCountRes.ProtoReflect.Descriptor instead.
func (*AccessCountRes) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *AccessCountRes) GetAccessCountList() []*AccessCount {
	if x != nil {
		return x.AccessCountList
	}
	return nil
}

type BookingRevenueReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GymId     string `protobuf:"bytes,1,opt,name=gymId,proto3" json:"gymId,omitempty"`
	StartDate string `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate   string `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
}

func (x *BookingRevenueReq) Reset() {
	*x = BookingRevenueReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingRevenueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRevenueReq) ProtoMessage() {}

func (x *BookingRevenueReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRevenueReq.ProtoReflect.Descriptor instead.
func (*BookingRevenueReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *BookingRevenueReq) GetGymId() string {
	if x != nil {
		return x.GymId
	}
	return ""
}

func (x *BookingRevenueReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *BookingRevenueReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type BookingRevenue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingDate    string  `protobuf:"bytes,1,opt,name=bookingDate,proto3" json:"bookingDate,omitempty"`
	AverageRevenue float32 `protobuf:"fixed32,2,opt,name=averageRevenue,proto3" json:"averageRevenue,omitempty"`
}

func (x *BookingRevenue) Reset() {
	*x = BookingRevenue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRevenue) ProtoMessage() {}

func (x *BookingRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRevenue.ProtoReflect.Descriptor instead.
func (*BookingRevenue) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *BookingRevenue) GetBookingDate() string {
	if x != nil {
		return x.BookingDate
	}
	return ""
}

func (x *BookingRevenue) GetAverageRevenue() float32 {
	if x != nil {
		return x.AverageRevenue
	}
	return 0
}

type BookingRevenueRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingRevenueList []*BookingRevenue `protobuf:"bytes,1,rep,name=bookingRevenueList,proto3" json:"bookingRevenueList,omitempty"`
}

func (x *BookingRevenueRes) Reset() {
	*x = BookingRevenueRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingRevenueRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRevenueRes) ProtoMessage() {}

func (x *BookingRevenueRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRevenueRes.ProtoReflect.Descriptor instead.
func (*BookingRevenueRes) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *BookingRevenueRes) GetBookingRevenueList() []*BookingRevenue {
	if x != nil {
		return x.BookingRevenueList
	}
	return nil
}

type SubscriptionCountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionID string `protobuf:"bytes,1,opt,name=subscriptionID,proto3" json:"subscriptionID,omitempty"`
	StartDate      string `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate        string `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
}

func (x *SubscriptionCountReq) Reset() {
	*x = SubscriptionCountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionCountReq) ProtoMessage() {}

func (x *SubscriptionCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionCountReq.ProtoReflect.Descriptor instead.
func (*SubscriptionCountReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *SubscriptionCountReq) GetSubscriptionID() string {
	if x != nil {
		return x.SubscriptionID
	}
	return ""
}

func (x *SubscriptionCountReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *SubscriptionCountReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type SubscriptionCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessDate  string `protobuf:"bytes,1,opt,name=accessDate,proto3" json:"accessDate,omitempty"`
	AccessCount int32  `protobuf:"varint,2,opt,name=accessCount,proto3" json:"accessCount,omitempty"`
}

func (x *SubscriptionCount) Reset() {
	*x = SubscriptionCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionCount) ProtoMessage() {}

func (x *SubscriptionCount) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionCount.ProtoReflect.Descriptor instead.
func (*SubscriptionCount) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *SubscriptionCount) GetAccessDate() string {
	if x != nil {
		return x.AccessDate
	}
	return ""
}

func (x *SubscriptionCount) GetAccessCount() int32 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

type SubscriptionCountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionCountList []*SubscriptionCount `protobuf:"bytes,1,rep,name=subscriptionCountList,proto3" json:"subscriptionCountList,omitempty"`
}

func (x *SubscriptionCountRes) Reset() {
	*x = SubscriptionCountRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionCountRes) ProtoMessage() {}

func (x *SubscriptionCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionCountRes.ProtoReflect.Descriptor instead.
func (*SubscriptionCountRes) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *SubscriptionCountRes) GetSubscriptionCountList() []*SubscriptionCount {
	if x != nil {
		return x.SubscriptionCountList
	}
	return nil
}

type BookingRevenueBySubscriptionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionID string `protobuf:"bytes,1,opt,name=subscriptionID,proto3" json:"subscriptionID,omitempty"`
	StartDate      string `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate        string `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
}

func (x *BookingRevenueBySubscriptionReq) Reset() {
	*x = BookingRevenueBySubscriptionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingRevenueBySubscriptionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRevenueBySubscriptionReq) ProtoMessage() {}

func (x *BookingRevenueBySubscriptionReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRevenueBySubscriptionReq.ProtoReflect.Descriptor instead.
func (*BookingRevenueBySubscriptionReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{9}
}

func (x *BookingRevenueBySubscriptionReq) GetSubscriptionID() string {
	if x != nil {
		return x.SubscriptionID
	}
	return ""
}

func (x *BookingRevenueBySubscriptionReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *BookingRevenueBySubscriptionReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type BookingRevenueBySubscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingDate    string  `protobuf:"bytes,1,opt,name=bookingDate,proto3" json:"bookingDate,omitempty"`
	AverageRevenue float32 `protobuf:"fixed32,2,opt,name=averageRevenue,proto3" json:"averageRevenue,omitempty"`
}

func (x *BookingRevenueBySubscription) Reset() {
	*x = BookingRevenueBySubscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingRevenueBySubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRevenueBySubscription) ProtoMessage() {}

func (x *BookingRevenueBySubscription) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRevenueBySubscription.ProtoReflect.Descriptor instead.
func (*BookingRevenueBySubscription) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{10}
}

func (x *BookingRevenueBySubscription) GetBookingDate() string {
	if x != nil {
		return x.BookingDate
	}
	return ""
}

func (x *BookingRevenueBySubscription) GetAverageRevenue() float32 {
	if x != nil {
		return x.AverageRevenue
	}
	return 0
}

type BookingRevenueBySubscriptionRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingRevenueBySubscriptionList []*BookingRevenueBySubscription `protobuf:"bytes,1,rep,name=bookingRevenueBySubscriptionList,proto3" json:"bookingRevenueBySubscriptionList,omitempty"`
}

func (x *BookingRevenueBySubscriptionRes) Reset() {
	*x = BookingRevenueBySubscriptionRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingRevenueBySubscriptionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRevenueBySubscriptionRes) ProtoMessage() {}

func (x *BookingRevenueBySubscriptionRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRevenueBySubscriptionRes.ProtoReflect.Descriptor instead.
func (*BookingRevenueBySubscriptionRes) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{11}
}

func (x *BookingRevenueBySubscriptionRes) GetBookingRevenueBySubscriptionList() []*BookingRevenueBySubscription {
	if x != nil {
		return x.BookingRevenueBySubscriptionList
	}
	return nil
}

type TotalMenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GymId string `protobuf:"bytes,1,opt,name=gymId,proto3" json:"gymId,omitempty"`
}

func (x *TotalMenReq) Reset() {
	*x = TotalMenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalMenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalMenReq) ProtoMessage() {}

func (x *TotalMenReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalMenReq.ProtoReflect.Descriptor instead.
func (*TotalMenReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{12}
}

func (x *TotalMenReq) GetGymId() string {
	if x != nil {
		return x.GymId
	}
	return ""
}

type TotalMen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMen int32  `protobuf:"varint,1,opt,name=totalMen,proto3" json:"totalMen,omitempty"`
	Gender   string `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"` // This is fine if you want to keep track of gender types
}

func (x *TotalMen) Reset() {
	*x = TotalMen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalMen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalMen) ProtoMessage() {}

func (x *TotalMen) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalMen.ProtoReflect.Descriptor instead.
func (*TotalMen) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{13}
}

func (x *TotalMen) GetTotalMen() int32 {
	if x != nil {
		return x.TotalMen
	}
	return 0
}

func (x *TotalMen) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type TotalMenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMenList []*TotalMen `protobuf:"bytes,1,rep,name=totalMenList,proto3" json:"totalMenList,omitempty"`
}

func (x *TotalMenRes) Reset() {
	*x = TotalMenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalMenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalMenRes) ProtoMessage() {}

func (x *TotalMenRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalMenRes.ProtoReflect.Descriptor instead.
func (*TotalMenRes) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{14}
}

func (x *TotalMenRes) GetTotalMenList() []*TotalMen {
	if x != nil {
		return x.TotalMenList
	}
	return nil
}

type TotalWomenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GymId string `protobuf:"bytes,1,opt,name=gymId,proto3" json:"gymId,omitempty"`
}

func (x *TotalWomenReq) Reset() {
	*x = TotalWomenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalWomenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalWomenReq) ProtoMessage() {}

func (x *TotalWomenReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalWomenReq.ProtoReflect.Descriptor instead.
func (*TotalWomenReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{15}
}

func (x *TotalWomenReq) GetGymId() string {
	if x != nil {
		return x.GymId
	}
	return ""
}

type TotalWomen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalWomen int32  `protobuf:"varint,1,opt,name=totalWomen,proto3" json:"totalWomen,omitempty"`
	Gender     string `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *TotalWomen) Reset() {
	*x = TotalWomen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalWomen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalWomen) ProtoMessage() {}

func (x *TotalWomen) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalWomen.ProtoReflect.Descriptor instead.
func (*TotalWomen) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{16}
}

func (x *TotalWomen) GetTotalWomen() int32 {
	if x != nil {
		return x.TotalWomen
	}
	return 0
}

func (x *TotalWomen) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type TotalWomenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalWomenList []*TotalWomen `protobuf:"bytes,1,rep,name=totalWomenList,proto3" json:"totalWomenList,omitempty"`
}

func (x *TotalWomenRes) Reset() {
	*x = TotalWomenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalWomenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalWomenRes) ProtoMessage() {}

func (x *TotalWomenRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalWomenRes.ProtoReflect.Descriptor instead.
func (*TotalWomenRes) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{17}
}

func (x *TotalWomenRes) GetTotalWomenList() []*TotalWomen {
	if x != nil {
		return x.TotalWomenList
	}
	return nil
}

type TotalMembersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GymId string `protobuf:"bytes,1,opt,name=gymId,proto3" json:"gymId,omitempty"`
}

func (x *TotalMembersReq) Reset() {
	*x = TotalMembersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalMembersReq) ProtoMessage() {}

func (x *TotalMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalMembersReq.ProtoReflect.Descriptor instead.
func (*TotalMembersReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{18}
}

func (x *TotalMembersReq) GetGymId() string {
	if x != nil {
		return x.GymId
	}
	return ""
}

type TotalMembers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMembers int32 `protobuf:"varint,1,opt,name=totalMembers,proto3" json:"totalMembers,omitempty"`
}

func (x *TotalMembers) Reset() {
	*x = TotalMembers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalMembers) ProtoMessage() {}

func (x *TotalMembers) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalMembers.ProtoReflect.Descriptor instead.
func (*TotalMembers) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{19}
}

func (x *TotalMembers) GetTotalMembers() int32 {
	if x != nil {
		return x.TotalMembers
	}
	return 0
}

type TotalMembersRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMembersList []*TotalMembers `protobuf:"bytes,1,rep,name=totalMembersList,proto3" json:"totalMembersList,omitempty"`
}

func (x *TotalMembersRes) Reset() {
	*x = TotalMembersRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalMembersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalMembersRes) ProtoMessage() {}

func (x *TotalMembersRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalMembersRes.ProtoReflect.Descriptor instead.
func (*TotalMembersRes) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{20}
}

func (x *TotalMembersRes) GetTotalMembersList() []*TotalMembers {
	if x != nil {
		return x.TotalMembersList
	}
	return nil
}

type TotalAmountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GymId string `protobuf:"bytes,1,opt,name=gymId,proto3" json:"gymId,omitempty"`
}

func (x *TotalAmountReq) Reset() {
	*x = TotalAmountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalAmountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalAmountReq) ProtoMessage() {}

func (x *TotalAmountReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalAmountReq.ProtoReflect.Descriptor instead.
func (*TotalAmountReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{21}
}

func (x *TotalAmountReq) GetGymId() string {
	if x != nil {
		return x.GymId
	}
	return ""
}

type TotalAmount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalAmount float32 `protobuf:"fixed32,1,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
}

func (x *TotalAmount) Reset() {
	*x = TotalAmount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalAmount) ProtoMessage() {}

func (x *TotalAmount) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalAmount.ProtoReflect.Descriptor instead.
func (*TotalAmount) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{22}
}

func (x *TotalAmount) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TotalAmountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalAmountList []*TotalAmount `protobuf:"bytes,1,rep,name=totalAmountList,proto3" json:"totalAmountList,omitempty"`
}

func (x *TotalAmountRes) Reset() {
	*x = TotalAmountRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalAmountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalAmountRes) ProtoMessage() {}

func (x *TotalAmountRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalAmountRes.ProtoReflect.Descriptor instead.
func (*TotalAmountRes) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{23}
}

func (x *TotalAmountRes) GetTotalAmountList() []*TotalAmount {
	if x != nil {
		return x.TotalAmountList
	}
	return nil
}

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{24}
}

type RevenueReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PercentageChange float32 `protobuf:"fixed32,1,opt,name=percentageChange,proto3" json:"percentageChange,omitempty"`
}

func (x *RevenueReq) Reset() {
	*x = RevenueReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevenueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevenueReq) ProtoMessage() {}

func (x *RevenueReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevenueReq.ProtoReflect.Descriptor instead.
func (*RevenueReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{25}
}

func (x *RevenueReq) GetPercentageChange() float32 {
	if x != nil {
		return x.PercentageChange
	}
	return 0
}

type MonthlyRevenue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year   int32   `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month  int32   `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Amount float32 `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *MonthlyRevenue) Reset() {
	*x = MonthlyRevenue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonthlyRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyRevenue) ProtoMessage() {}

func (x *MonthlyRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyRevenue.ProtoReflect.Descriptor instead.
func (*MonthlyRevenue) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{26}
}

func (x *MonthlyRevenue) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MonthlyRevenue) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *MonthlyRevenue) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type MonthlyRevenueRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MonthlyRevenue []*MonthlyRevenue `protobuf:"bytes,1,rep,name=monthlyRevenue,proto3" json:"monthlyRevenue,omitempty"`
}

func (x *MonthlyRevenueRes) Reset() {
	*x = MonthlyRevenueRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonthlyRevenueRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyRevenueRes) ProtoMessage() {}

func (x *MonthlyRevenueRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyRevenueRes.ProtoReflect.Descriptor instead.
func (*MonthlyRevenueRes) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{27}
}

func (x *MonthlyRevenueRes) GetMonthlyRevenue() []*MonthlyRevenue {
	if x != nil {
		return x.MonthlyRevenue
	}
	return nil
}

type TotalGenderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GymId string `protobuf:"bytes,1,opt,name=gymId,proto3" json:"gymId,omitempty"`
}

func (x *TotalGenderReq) Reset() {
	*x = TotalGenderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalGenderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalGenderReq) ProtoMessage() {}

func (x *TotalGenderReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalGenderReq.ProtoReflect.Descriptor instead.
func (*TotalGenderReq) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{28}
}

func (x *TotalGenderReq) GetGymId() string {
	if x != nil {
		return x.GymId
	}
	return ""
}

type GenderCountsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMen   int32 `protobuf:"varint,1,opt,name=totalMen,proto3" json:"totalMen,omitempty"`
	TotalWomen int32 `protobuf:"varint,2,opt,name=totalWomen,proto3" json:"totalWomen,omitempty"`
}

func (x *GenderCountsRes) Reset() {
	*x = GenderCountsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dashboard_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenderCountsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenderCountsRes) ProtoMessage() {}

func (x *GenderCountsRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenderCountsRes.ProtoReflect.Descriptor instead.
func (*GenderCountsRes) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{29}
}

func (x *GenderCountsRes) GetTotalMen() int32 {
	if x != nil {
		return x.TotalMen
	}
	return 0
}

func (x *GenderCountsRes) GetTotalWomen() int32 {
	if x != nil {
		return x.TotalWomen
	}
	return 0
}

var File_dashboard_proto protoreflect.FileDescriptor

var file_dashboard_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x5e, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x79, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x79, 0x6d, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x4f, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x44, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4d, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x0f, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x61, 0x0a, 0x11, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x67, 0x79, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x79, 0x6d,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x5a, 0x0a, 0x0e, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x22, 0x59, 0x0a, 0x11, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x12, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x12, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x76, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x55, 0x0a, 0x11, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x44, 0x61, 0x74, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x65, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x4d, 0x0a, 0x15, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x15, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x1f, 0x42, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x42, 0x79, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x68, 0x0a, 0x1c, 0x42,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x42, 0x79, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x76, 0x65, 0x6e, 0x75, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x1f, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x42, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x6e, 0x0a, 0x20, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x42, 0x79, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x42, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x20, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x42, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x0b, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x4d, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x79, 0x6d, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x79, 0x6d, 0x49, 0x64, 0x22, 0x3e,
	0x0a, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x41,
	0x0a, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a,
	0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x4d, 0x65, 0x6e, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x25, 0x0a, 0x0d, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x6f, 0x6d, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x79, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x67, 0x79, 0x6d, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x57, 0x6f, 0x6d, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57,
	0x6f, 0x6d, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x57, 0x6f, 0x6d, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x49,
	0x0a, 0x0d, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x6f, 0x6d, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12,
	0x38, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x6f, 0x6d, 0x65, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x57, 0x6f, 0x6d, 0x65, 0x6e, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x57, 0x6f, 0x6d, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x0f, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x67, 0x79, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x79, 0x6d,
	0x49, 0x64, 0x22, 0x32, 0x0a, 0x0c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x51, 0x0a, 0x0f, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x10, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x10, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x0e, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x67,
	0x79, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x79, 0x6d, 0x49,
	0x64, 0x22, 0x2f, 0x0a, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x4d, 0x0a, 0x0e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x06, 0x0a, 0x04, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x0a, 0x52, 0x65, 0x76,
	0x65, 0x6e, 0x75, 0x65, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x10, 0x70, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x74, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x10, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x22, 0x52, 0x0a, 0x0e, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x52, 0x65,
	0x76, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x51, 0x0a, 0x11, 0x4d, 0x6f, 0x6e, 0x74, 0x68,
	0x6c, 0x79, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0e,
	0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4d, 0x6f, 0x6e, 0x74,
	0x68, 0x6c, 0x79, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x0e, 0x6d, 0x6f, 0x6e, 0x74,
	0x68, 0x6c, 0x79, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x67, 0x79, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x79, 0x6d,
	0x49, 0x64, 0x22, 0x4d, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x6f, 0x6d, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x6f, 0x6d, 0x65,
	0x6e, 0x32, 0xb6, 0x06, 0x0a, 0x10, 0x44, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x44, 0x61, 0x69,
	0x6c, 0x79, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x12, 0x57, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x76, 0x65,
	0x6e, 0x75, 0x65, 0x42, 0x79, 0x44, 0x61, 0x79, 0x12, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65, 0x73, 0x12, 0x5d, 0x0a, 0x23, 0x47, 0x65,
	0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x42, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x12, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x76, 0x0a, 0x26, 0x47, 0x65, 0x74,
	0x44, 0x61, 0x69, 0x6c, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x76, 0x65,
	0x6e, 0x75, 0x65, 0x42, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x12, 0x25, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x42, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65,
	0x42, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x12, 0x30, 0x0a, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6e, 0x12, 0x11, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x6f, 0x6d, 0x65,
	0x6e, 0x12, 0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x6f,
	0x6d, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x57, 0x6f, 0x6d, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0c, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x15, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x0b, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x25, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75,
	0x73, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x0a, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x1a, 0x10, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65, 0x71, 0x12, 0x3d, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x0a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x56, 0x6f, 0x69,
	0x64, 0x1a, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79,
	0x52, 0x65, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_proto_rawDescData = file_dashboard_proto_rawDesc
)

func file_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(file_dashboard_proto_rawDescData)
	})
	return file_dashboard_proto_rawDescData
}

var file_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_dashboard_proto_goTypes = []any{
	(*AccessCountReq)(nil),                  // 0: auth.AccessCountReq
	(*AccessCount)(nil),                     // 1: auth.AccessCount
	(*AccessCountRes)(nil),                  // 2: auth.AccessCountRes
	(*BookingRevenueReq)(nil),               // 3: auth.BookingRevenueReq
	(*BookingRevenue)(nil),                  // 4: auth.BookingRevenue
	(*BookingRevenueRes)(nil),               // 5: auth.BookingRevenueRes
	(*SubscriptionCountReq)(nil),            // 6: auth.SubscriptionCountReq
	(*SubscriptionCount)(nil),               // 7: auth.SubscriptionCount
	(*SubscriptionCountRes)(nil),            // 8: auth.SubscriptionCountRes
	(*BookingRevenueBySubscriptionReq)(nil), // 9: auth.BookingRevenueBySubscriptionReq
	(*BookingRevenueBySubscription)(nil),    // 10: auth.BookingRevenueBySubscription
	(*BookingRevenueBySubscriptionRes)(nil), // 11: auth.BookingRevenueBySubscriptionRes
	(*TotalMenReq)(nil),                     // 12: auth.TotalMenReq
	(*TotalMen)(nil),                        // 13: auth.TotalMen
	(*TotalMenRes)(nil),                     // 14: auth.TotalMenRes
	(*TotalWomenReq)(nil),                   // 15: auth.TotalWomenReq
	(*TotalWomen)(nil),                      // 16: auth.TotalWomen
	(*TotalWomenRes)(nil),                   // 17: auth.TotalWomenRes
	(*TotalMembersReq)(nil),                 // 18: auth.TotalMembersReq
	(*TotalMembers)(nil),                    // 19: auth.TotalMembers
	(*TotalMembersRes)(nil),                 // 20: auth.TotalMembersRes
	(*TotalAmountReq)(nil),                  // 21: auth.TotalAmountReq
	(*TotalAmount)(nil),                     // 22: auth.TotalAmount
	(*TotalAmountRes)(nil),                  // 23: auth.TotalAmountRes
	(*Void)(nil),                            // 24: auth.Void
	(*RevenueReq)(nil),                      // 25: auth.RevenueReq
	(*MonthlyRevenue)(nil),                  // 26: auth.MonthlyRevenue
	(*MonthlyRevenueRes)(nil),               // 27: auth.MonthlyRevenueRes
	(*TotalGenderReq)(nil),                  // 28: auth.TotalGenderReq
	(*GenderCountsRes)(nil),                 // 29: auth.GenderCountsRes
}
var file_dashboard_proto_depIdxs = []int32{
	1,  // 0: auth.AccessCountRes.accessCountList:type_name -> auth.AccessCount
	4,  // 1: auth.BookingRevenueRes.bookingRevenueList:type_name -> auth.BookingRevenue
	7,  // 2: auth.SubscriptionCountRes.subscriptionCountList:type_name -> auth.SubscriptionCount
	10, // 3: auth.BookingRevenueBySubscriptionRes.bookingRevenueBySubscriptionList:type_name -> auth.BookingRevenueBySubscription
	13, // 4: auth.TotalMenRes.totalMenList:type_name -> auth.TotalMen
	16, // 5: auth.TotalWomenRes.totalWomenList:type_name -> auth.TotalWomen
	19, // 6: auth.TotalMembersRes.totalMembersList:type_name -> auth.TotalMembers
	22, // 7: auth.TotalAmountRes.totalAmountList:type_name -> auth.TotalAmount
	26, // 8: auth.MonthlyRevenueRes.monthlyRevenue:type_name -> auth.MonthlyRevenue
	0,  // 9: auth.DashboardService.GetDailyPersonalAccessCount:input_type -> auth.AccessCountReq
	3,  // 10: auth.DashboardService.GetDailyPersonalBookingRevenueByDay:input_type -> auth.BookingRevenueReq
	6,  // 11: auth.DashboardService.GetDailyAccessCountBySubscriptionID:input_type -> auth.SubscriptionCountReq
	9,  // 12: auth.DashboardService.GetDailyBookingRevenueBySubscriptionID:input_type -> auth.BookingRevenueBySubscriptionReq
	12, // 13: auth.DashboardService.TotalMen:input_type -> auth.TotalMenReq
	15, // 14: auth.DashboardService.TotalWomen:input_type -> auth.TotalWomenReq
	18, // 15: auth.DashboardService.TotalMembers:input_type -> auth.TotalMembersReq
	21, // 16: auth.DashboardService.TotalAmount:input_type -> auth.TotalAmountReq
	24, // 17: auth.DashboardService.CompareCurrentAndPreviousMonthRevenue:input_type -> auth.Void
	24, // 18: auth.DashboardService.GetMonthlyRevenueStats:input_type -> auth.Void
	28, // 19: auth.DashboardService.GetGenderCounts:input_type -> auth.TotalGenderReq
	2,  // 20: auth.DashboardService.GetDailyPersonalAccessCount:output_type -> auth.AccessCountRes
	5,  // 21: auth.DashboardService.GetDailyPersonalBookingRevenueByDay:output_type -> auth.BookingRevenueRes
	8,  // 22: auth.DashboardService.GetDailyAccessCountBySubscriptionID:output_type -> auth.SubscriptionCountRes
	11, // 23: auth.DashboardService.GetDailyBookingRevenueBySubscriptionID:output_type -> auth.BookingRevenueBySubscriptionRes
	14, // 24: auth.DashboardService.TotalMen:output_type -> auth.TotalMenRes
	17, // 25: auth.DashboardService.TotalWomen:output_type -> auth.TotalWomenRes
	20, // 26: auth.DashboardService.TotalMembers:output_type -> auth.TotalMembersRes
	23, // 27: auth.DashboardService.TotalAmount:output_type -> auth.TotalAmountRes
	25, // 28: auth.DashboardService.CompareCurrentAndPreviousMonthRevenue:output_type -> auth.RevenueReq
	27, // 29: auth.DashboardService.GetMonthlyRevenueStats:output_type -> auth.MonthlyRevenueRes
	29, // 30: auth.DashboardService.GetGenderCounts:output_type -> auth.GenderCountsRes
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_dashboard_proto_init() }
func file_dashboard_proto_init() {
	if File_dashboard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dashboard_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AccessCountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AccessCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AccessCountRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BookingRevenueReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BookingRevenue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*BookingRevenueRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SubscriptionCountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SubscriptionCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SubscriptionCountRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*BookingRevenueBySubscriptionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*BookingRevenueBySubscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*BookingRevenueBySubscriptionRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*TotalMenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*TotalMen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*TotalMenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*TotalWomenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*TotalWomen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*TotalWomenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*TotalMembersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*TotalMembers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*TotalMembersRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*TotalAmountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*TotalAmount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*TotalAmountRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*RevenueReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*MonthlyRevenue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*MonthlyRevenueRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*TotalGenderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dashboard_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*GenderCountsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dashboard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_proto = out.File
	file_dashboard_proto_rawDesc = nil
	file_dashboard_proto_goTypes = nil
	file_dashboard_proto_depIdxs = nil
}
